export const memberRegisterFormData = {
  employee_number: "",
  kor_name: "",
  eng_name: "",
  phone_number: "",
  address: {
    address: "",
    jibun_address: "",
    zone_code: "",
    detail_address: "",
  },
  rrn_front: "",
  rrn_back: "",
  sex: "남성",
  email: "",
  military: {
    division: "",
    army: "",
    rank: "",
  },
  quarter: "",
  department: "",
  team: "",
  position: "",
  rank: "",
  date_of_joining: "",
  career: [
    {
      company_name: "",
      join_date: "",
      leave_date: "",
      job: "",
      depart: "",
      rank: "",
    },
  ],
  edu: [
    {
      school_classification: "",
      school_name: "",
      collage: "",
      graduation_status: "",
      admission_date: "",
      graduation_date: "",
    },
  ],
};
